services:
  - type: web
    name: icu-occupancy-predictor
    env: python
    buildCommand: pip install -r deployment/requirements.txt
    startCommand: gunicorn --worker-class eventlet --workers 1 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: icuconnectdb
          property: connectionString
    databases:
      - name: icuconnectdb
        databaseName: icuconnectdb
        user: flaskuser
